task:
  freebsd_instance:
    matrix:
      image: freebsd-12-4-release-amd64
      image: freebsd-13-1-release-amd64
  env:
    CIRRUS_SHELL: /bin/sh
    matrix:
      - RUST_VERSION: stable
  install_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --default-toolchain ${RUST_VERSION}
  cargo_cache:
    folder: $HOME/.cargo/registry
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all-features
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all-features
  before_cache_script: rm -rf $HOME/.cargo/registry/index
