setup: &FREEBSD_SETUP
  env:
    HOME: /tmp # cargo needs it
    RUST_BACKTRACE: full  # Better info for debugging test failures.
  setup_script:
    - pkg install -y llvm
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}

build: &BUILD_TEST
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env || true
    - cargo build ${FEATURES}
  test_script:
    - . $HOME/.cargo/env || true
    - cargo test ${FEATURES}

# It's important to test on FreeBSD 14 because it has a different libnv.so
# version than FreeBSD 13
task:
  name: FreeBSD 14
  env:
    FEATURES: --all-features
  matrix:
    - name: FreeBSD 14 features=both nightly
      env:
        VERSION: nightly
    - name: FreeBSD 14 features=both stable
      env:
        VERSION: stable
  freebsd_instance:
    image_family: freebsd-14-0-snap
  << : *FREEBSD_SETUP
  << : *BUILD_TEST
  clippy_script:
    - . $HOME/.cargo/env
    - if rustc --version | grep -q nightly; then
    -   rustup component add clippy
    -   cargo clippy ${FEATURES} --all-targets
    - fi
  minver_script:
    - . $HOME/.cargo/env
    - if rustc --version | grep -q nightly; then
    -   cargo update -Zdirect-minimal-versions
    -   cargo check --all-targets ${FEATURES}
    - fi
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: FreeBSD 13
  env:
    VERSION: stable
  matrix:
    - name: FreeBSD 13 features=libnv stable
      env:
        FEATURES: --no-default-features --features=libnv
    - name: FreeBSD 13 features=nvpair stable
      env:
        FEATURES: --no-default-features --features=nvpair
  freebsd_instance:
    image: freebsd-13-3-release-amd64
  << : *FREEBSD_SETUP
  << : *BUILD_TEST
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: Linux features=nvpair
  container:
    image: rust:latest
  env:
    FEATURES: --no-default-features --features=nvpair
  setup_script:
    - cat /etc/debian_version
    - echo "deb http://deb.debian.org/debian bookworm main contrib" >> /etc/apt/sources.list
    - apt update
    - apt search nvpair
    - apt-get -y  install libnvpair3linux libzfslinux-dev zfsutils-linux
  << : *BUILD_TEST
  before_cache_script: rm -rf $HOME/.cargo/registry/index
