task:
  freebsd_instance:
    matrix:
      image: freebsd-12-4-release-amd64
      image: freebsd-13-1-release-amd64
  env:
    CIRRUS_SHELL: /bin/sh
    RUST_VERSION: stable
    matrix:
      FEATURES: libnv
      FEATURES: nvpair
  install_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --default-toolchain ${RUST_VERSION}
    - pkg install -y llvm
  cargo_cache:
    folder: $HOME/.cargo/registry
  build_script:
    - . $HOME/.cargo/env
    - cargo build --no-default-features --features=$FEATURES
  test_script:
    - . $HOME/.cargo/env
    - cargo test --no-default-features --features=$FEATURES
  before_cache_script: rm -rf $HOME/.cargo/registry/index
