indent_style = "Block"
use_small_heuristics = "Max"
comment_width = 100
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
fn_single_line = true
imports_indent = "Visual"
imports_granularity = "Crate"
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
unstable_features = true
inline_attribute_width = 50
