/* automatically generated by rust-bindgen 0.72.1 */

#[doc = r" If Bindgen could only determine the size and alignment of a"]
#[doc = r" type, it is represented like this."]
#[derive(PartialEq, Copy, Clone, Debug, Hash)]
#[repr(C)]
pub struct __BindgenOpaqueArray<T: Copy, const N: usize>(pub [T; N]);
impl<T: Copy + Default, const N: usize> Default for __BindgenOpaqueArray<T, N> {
    fn default() -> Self {
        Self([<T as Default>::default(); N])
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FreeBSD_nvlist {
    _unused: [u8; 0],
}
pub type FreeBSD_nvlist_t = nvlist_t;
pub type nvlist_t = FreeBSD_nvlist;
pub type FILE = __BindgenOpaqueArray<u64, 39usize>;
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_create"]
    pub fn nvlist_create(flags: ::std::os::raw::c_int) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_destroy"]
    pub fn nvlist_destroy(nvl: *mut FreeBSD_nvlist_t);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_error"]
    pub fn nvlist_error(nvl: *const FreeBSD_nvlist_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_empty"]
    pub fn nvlist_empty(nvl: *const FreeBSD_nvlist_t) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_flags"]
    pub fn nvlist_flags(nvl: *const FreeBSD_nvlist_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_set_error"]
    pub fn nvlist_set_error(nvl: *mut FreeBSD_nvlist_t, error: ::std::os::raw::c_int);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_clone"]
    pub fn nvlist_clone(nvl: *const FreeBSD_nvlist_t) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_dump"]
    pub fn nvlist_dump(nvl: *const FreeBSD_nvlist_t, fd: ::std::os::raw::c_int);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_fdump"]
    pub fn nvlist_fdump(nvl: *const FreeBSD_nvlist_t, fp: *mut FILE);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_size"]
    pub fn nvlist_size(nvl: *const FreeBSD_nvlist_t) -> usize;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_pack"]
    pub fn nvlist_pack(
        nvl: *const FreeBSD_nvlist_t,
        sizep: *mut usize,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_unpack"]
    pub fn nvlist_unpack(
        buf: *const ::std::os::raw::c_void,
        size: usize,
        flags: ::std::os::raw::c_int,
    ) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_send"]
    pub fn nvlist_send(
        sock: ::std::os::raw::c_int,
        nvl: *const FreeBSD_nvlist_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_recv"]
    pub fn nvlist_recv(
        sock: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_xfer"]
    pub fn nvlist_xfer(
        sock: ::std::os::raw::c_int,
        nvl: *mut FreeBSD_nvlist_t,
        flags: ::std::os::raw::c_int,
    ) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_next"]
    pub fn nvlist_next(
        nvl: *const FreeBSD_nvlist_t,
        typep: *mut ::std::os::raw::c_int,
        cookiep: *mut *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_parent"]
    pub fn nvlist_get_parent(
        nvl: *const FreeBSD_nvlist_t,
        cookiep: *mut *mut ::std::os::raw::c_void,
    ) -> *const FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_array_next"]
    pub fn nvlist_get_array_next(nvl: *const FreeBSD_nvlist_t) -> *const FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_in_array"]
    pub fn nvlist_in_array(nvl: *const FreeBSD_nvlist_t) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_pararr"]
    pub fn nvlist_get_pararr(
        nvl: *const FreeBSD_nvlist_t,
        cookiep: *mut *mut ::std::os::raw::c_void,
    ) -> *const FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists"]
    pub fn nvlist_exists(nvl: *const FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char)
        -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_type"]
    pub fn nvlist_exists_type(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_null"]
    pub fn nvlist_exists_null(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_bool"]
    pub fn nvlist_exists_bool(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_number"]
    pub fn nvlist_exists_number(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_string"]
    pub fn nvlist_exists_string(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_nvlist"]
    pub fn nvlist_exists_nvlist(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_binary"]
    pub fn nvlist_exists_binary(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_bool_array"]
    pub fn nvlist_exists_bool_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_number_array"]
    pub fn nvlist_exists_number_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_string_array"]
    pub fn nvlist_exists_string_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_nvlist_array"]
    pub fn nvlist_exists_nvlist_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_descriptor"]
    pub fn nvlist_exists_descriptor(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_exists_descriptor_array"]
    pub fn nvlist_exists_descriptor_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_null"]
    pub fn nvlist_add_null(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_bool"]
    pub fn nvlist_add_bool(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: bool,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_number"]
    pub fn nvlist_add_number(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: u64,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_string"]
    pub fn nvlist_add_string(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_stringf"]
    pub fn nvlist_add_stringf(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        valuefmt: *const ::std::os::raw::c_char,
        ...
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_nvlist"]
    pub fn nvlist_add_nvlist(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const FreeBSD_nvlist_t,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_binary"]
    pub fn nvlist_add_binary(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_void,
        size: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_bool_array"]
    pub fn nvlist_add_bool_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const bool,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_number_array"]
    pub fn nvlist_add_number_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const u64,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_string_array"]
    pub fn nvlist_add_string_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const *const ::std::os::raw::c_char,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_nvlist_array"]
    pub fn nvlist_add_nvlist_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const *const FreeBSD_nvlist_t,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_descriptor"]
    pub fn nvlist_add_descriptor(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_add_descriptor_array"]
    pub fn nvlist_add_descriptor_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_int,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_append_bool_array"]
    pub fn nvlist_append_bool_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: bool,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_append_number_array"]
    pub fn nvlist_append_number_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: u64,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_append_string_array"]
    pub fn nvlist_append_string_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_append_nvlist_array"]
    pub fn nvlist_append_nvlist_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *const FreeBSD_nvlist_t,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_append_descriptor_array"]
    pub fn nvlist_append_descriptor_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_string"]
    pub fn nvlist_move_string(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_nvlist"]
    pub fn nvlist_move_nvlist(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut FreeBSD_nvlist_t,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_binary"]
    pub fn nvlist_move_binary(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_void,
        size: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_bool_array"]
    pub fn nvlist_move_bool_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut bool,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_string_array"]
    pub fn nvlist_move_string_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut *mut ::std::os::raw::c_char,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_nvlist_array"]
    pub fn nvlist_move_nvlist_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut *mut FreeBSD_nvlist_t,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_number_array"]
    pub fn nvlist_move_number_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut u64,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_descriptor"]
    pub fn nvlist_move_descriptor(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_move_descriptor_array"]
    pub fn nvlist_move_descriptor_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_int,
        nitems: usize,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_bool"]
    pub fn nvlist_get_bool(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_number"]
    pub fn nvlist_get_number(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> u64;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_string"]
    pub fn nvlist_get_string(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_nvlist"]
    pub fn nvlist_get_nvlist(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> *const FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_binary"]
    pub fn nvlist_get_binary(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        sizep: *mut usize,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_bool_array"]
    pub fn nvlist_get_bool_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *const bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_number_array"]
    pub fn nvlist_get_number_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *const u64;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_string_array"]
    pub fn nvlist_get_string_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *const *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_nvlist_array"]
    pub fn nvlist_get_nvlist_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *const *const FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_descriptor"]
    pub fn nvlist_get_descriptor(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_get_descriptor_array"]
    pub fn nvlist_get_descriptor_array(
        nvl: *const FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *const ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_bool"]
    pub fn nvlist_take_bool(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_number"]
    pub fn nvlist_take_number(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> u64;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_string"]
    pub fn nvlist_take_string(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_nvlist"]
    pub fn nvlist_take_nvlist(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_binary"]
    pub fn nvlist_take_binary(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        sizep: *mut usize,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_bool_array"]
    pub fn nvlist_take_bool_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *mut bool;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_number_array"]
    pub fn nvlist_take_number_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *mut u64;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_string_array"]
    pub fn nvlist_take_string_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_nvlist_array"]
    pub fn nvlist_take_nvlist_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *mut *mut FreeBSD_nvlist_t;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_descriptor"]
    pub fn nvlist_take_descriptor(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_take_descriptor_array"]
    pub fn nvlist_take_descriptor_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        nitemsp: *mut usize,
    ) -> *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free"]
    pub fn nvlist_free(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_type"]
    pub fn nvlist_free_type(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_null"]
    pub fn nvlist_free_null(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_bool"]
    pub fn nvlist_free_bool(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_number"]
    pub fn nvlist_free_number(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_string"]
    pub fn nvlist_free_string(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_nvlist"]
    pub fn nvlist_free_nvlist(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_binary"]
    pub fn nvlist_free_binary(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_bool_array"]
    pub fn nvlist_free_bool_array(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_number_array"]
    pub fn nvlist_free_number_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_string_array"]
    pub fn nvlist_free_string_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_nvlist_array"]
    pub fn nvlist_free_nvlist_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_binary_array"]
    pub fn nvlist_free_binary_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_descriptor"]
    pub fn nvlist_free_descriptor(nvl: *mut FreeBSD_nvlist_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[link_name = "FreeBSD_nvlist_free_descriptor_array"]
    pub fn nvlist_free_descriptor_array(
        nvl: *mut FreeBSD_nvlist_t,
        name: *const ::std::os::raw::c_char,
    );
}
